const objCliente = {
  id: '',
  nomeFantasia: '',
  razaoSocial: '',
  endereco: '',
  num: '',
  complemento: '',
  bairro: '',
  cep: '',
  cidade: '',
  codMun: '',
  estado: '',
  PFPJ: '',
  cnpj_cpf: '',
  inscricao: '',
  contato1: '',
  contato2: '',
  telefone1: '',
  telefone2: '',
  email: '',
  site: '',
  instagram: '',
  tabela: '',
  mark: '',
  aniversario: '',
  tamPadrao: '',
  tamAltura: '',
  tamBusto: '',
  tamQuadril: '',
  tamOmbro: '',
  tamCompBraco: '',
  tamLargBraco: '',
  tamCoxa: '',
  codSite: '',
};
export default objCliente;
