const objProduto = {
  id: '',
  ref: '',
  gtin: '',
  ncm: '',
  ativo: '',
  nome: '',
  nomeSite: '',
  nomeEncomenda: '',
  descricaoLonga: '',
  descricaoCurta: '',
  marca: '',
  colecao: '',
  categoria: '',
  subCategoria: '',
  faixaEtaria: '',
  modelagem: '',
  decote: '',
  Alca: '',
  Ombro: '',
  tipoManga: '',
  compManga: '',
  barraManga: '',
  compPeca: '',
  barraPeca: '',
  tipoSaia: '',
  cor: [],
  partes: '',
  Observacao: '',
  qtdeMin: 0,
  peso: 0,
  comprimento: 0,
  largura: 0,
  altura: 0,
  unidade: '',
  aliqICMS: 0,
  aliqPIS: 0,
  aliqCofins: 0,
  produtosFilhos: [],
};

export default objProduto;
